### PR TITLE
Images

### PR DESCRIPTION
**Pull request by stephaniewillhide**

### CODE REVIEW

**Comment by stephaniewillhide** [comment]
Hey @acohen, could i get your feedback on this? I'm afraid I went too heavy on the Canva instruction imgs. Thanks!

**Comment by stephaniewillhide** [comment]
Hey @acohen, can you review this? LMK if any more updates need to be made!

**Comment by acohen** [comment]
@stephaniewillhide Looks good! I made some minor edits to the content. I think we can combine the github images, cause the text in between is lost, both the branch and upload buttons are in the same image. :)

**Comment by stephaniewillhide** [comment]
Thanks @acohen! These edits look good - thanks for finding that typo, too. Good point about the one image. Passing to @dirkkelly to review.

**Pull request merged**
